const category = {
  api: 'mtop.global.merchant.mobile.product.publish.categoryopts',
  data: {
    context: {},
    model: [
      {
        path: ['Groceries', 'Breakfast Cereals & Spreads', 'Granola'],
        spell: 'Granola',
        idpath: [8229, 13035, 13038],
        name: 'Granola',
        disabled: false,
        id: 13038,
        leaf: true,
      },
    ],
    pageEnd: true,
    totalPage: 0,
  },
  ret: ['SUCCESS::调用成功'],
  v: '1.0',
}

const categoryList = {
  api: 'mtop.global.merchant.mobile.product.publish.categoryopts',
  data: {
    context: {},
    model: [
      {
        path: ['Kitchen & Dining'],
        spell: 'Kitchen & Dining',
        idpath: [22394],
        name: 'Kitchen & Dining',
        disabled: false,
        id: 22394,
        leaf: false,
      },
      {
        path: ['Sports & Outdoors'],
        spell: 'Sports & Outdoors',
        idpath: [4623],
        name: 'Sports & Outdoors',
        disabled: false,
        id: 4623,
        leaf: false,
      },
      {
        path: ['Digital Utilities'],
        spell: 'Digital Utilities',
        idpath: [10100058],
        name: 'Digital Utilities',
        disabled: false,
        id: 10100058,
        leaf: false,
      },
      {
        path: ['Services'],
        spell: 'Services',
        idpath: [10100047],
        name: 'Services',
        disabled: false,
        id: 10100047,
        leaf: false,
      },
      {
        path: ['Motors'],
        spell: 'Motors',
        idpath: [8228],
        name: 'Motors',
        disabled: false,
        id: 8228,
        leaf: false,
      },
      {
        path: ['Groceries'],
        spell: 'Groceries',
        idpath: [8229],
        name: 'Groceries',
        disabled: false,
        id: 8229,
        leaf: false,
      },
      {
        path: ['Fashion Accessories'],
        spell: 'Fashion Accessories',
        idpath: [13604],
        name: 'Fashion Accessories',
        disabled: false,
        id: 13604,
        leaf: false,
      },
      {
        path: ['Pet Supplies'],
        spell: 'Pet Supplies',
        idpath: [21907],
        name: 'Pet Supplies',
        disabled: false,
        id: 21907,
        leaf: false,
      },
      {
        path: ['Stationery, Craft & Gift Cards'],
        spell: 'Stationery, Craft & Gift Cards',
        idpath: [22393],
        name: 'Stationery, Craft & Gift Cards',
        disabled: false,
        id: 22393,
        leaf: false,
      },
      {
        path: ['Free Sample (Flexi Combo)'],
        spell: 'Free Sample (Flexi Combo)',
        idpath: [25012],
        name: 'Free Sample (Flexi Combo)',
        disabled: false,
        id: 25012,
        leaf: true,
      },
      {
        path: ['Special Digital Products'],
        spell: 'Special Digital Products',
        idpath: [25014],
        name: 'Special Digital Products',
        disabled: false,
        id: 25014,
        leaf: false,
      },
      {
        path: ['Service Product'],
        spell: 'Service Product',
        idpath: [25018],
        name: 'Service Product',
        disabled: false,
        id: 25018,
        leaf: true,
      },
      {
        path: ['Surprise Box'],
        spell: 'Surprise Box',
        idpath: [25061],
        name: 'Surprise Box',
        disabled: false,
        id: 25061,
        leaf: true,
      },
      {
        path: ['Sports Shoes and Clothing'],
        spell: 'Sports Shoes and Clothing',
        idpath: [42062401],
        name: 'Sports Shoes and Clothing',
        disabled: false,
        id: 42062401,
        leaf: false,
      },
      {
        path: ['Electronics Accessories'],
        spell: 'Electronics Accessories',
        idpath: [42062201],
        name: 'Electronics Accessories',
        disabled: false,
        id: 42062201,
        leaf: false,
      },
      {
        path: ["Kids' Shoes and Clothing"],
        spell: "Kids' Shoes and Clothing",
        idpath: [62188201],
        name: "Kids' Shoes and Clothing",
        disabled: false,
        id: 62188201,
        leaf: false,
      },
      {
        path: ['Mobiles & Tablets'],
        spell: 'Mobiles & Tablets',
        idpath: [5116],
        name: 'Mobiles & Tablets',
        disabled: false,
        id: 5116,
        leaf: false,
      },
      {
        path: ['Computers & Laptops'],
        spell: 'Computers & Laptops',
        idpath: [5141],
        name: 'Computers & Laptops',
        disabled: false,
        id: 5141,
        leaf: false,
      },
      {
        path: ['Cameras & Drones'],
        spell: 'Cameras & Drones',
        idpath: [5185],
        name: 'Cameras & Drones',
        disabled: false,
        id: 5185,
        leaf: false,
      },
      {
        path: ['Televisions & Videos'],
        spell: 'Televisions & Videos',
        idpath: [5222],
        name: 'Televisions & Videos',
        disabled: false,
        id: 5222,
        leaf: false,
      },
      {
        path: ['Small Appliances'],
        spell: 'Small Appliances',
        idpath: [5235],
        name: 'Small Appliances',
        disabled: false,
        id: 5235,
        leaf: false,
      },
      {
        path: ['Bags and Travel'],
        spell: 'Bags and Travel',
        idpath: [6820],
        name: 'Bags and Travel',
        disabled: false,
        id: 6820,
        leaf: false,
      },
      {
        path: ['Media, Music & Books'],
        spell: 'Media, Music & Books',
        idpath: [6823],
        name: 'Media, Music & Books',
        disabled: false,
        id: 6823,
        leaf: false,
      },
      {
        path: ["Women's Shoes and Clothing"],
        spell: "Women's Shoes and Clothing",
        idpath: [6851],
        name: "Women's Shoes and Clothing",
        disabled: false,
        id: 6851,
        leaf: false,
      },
      {
        path: ['Beauty'],
        spell: 'Beauty',
        idpath: [7644],
        name: 'Beauty',
        disabled: false,
        id: 7644,
        leaf: false,
      },
      {
        path: ['Lighting & Décor'],
        spell: 'Lighting & Décor',
        idpath: [10100083],
        name: 'Lighting & Décor',
        disabled: false,
        id: 10100083,
        leaf: false,
      },
      {
        path: ['Monitors & Printers'],
        spell: 'Monitors & Printers',
        idpath: [10100380],
        name: 'Monitors & Printers',
        disabled: false,
        id: 10100380,
        leaf: false,
      },
      {
        path: ['Smart Devices'],
        spell: 'Smart Devices',
        idpath: [10100412],
        name: 'Smart Devices',
        disabled: false,
        id: 10100412,
        leaf: false,
      },
      {
        path: ['Data Storage'],
        spell: 'Data Storage',
        idpath: [10100386],
        name: 'Data Storage',
        disabled: false,
        id: 10100386,
        leaf: false,
      },
      {
        path: ['Audio'],
        spell: 'Audio',
        idpath: [10100387],
        name: 'Audio',
        disabled: false,
        id: 10100387,
        leaf: false,
      },
      {
        path: ['Outdoor & Garden'],
        spell: 'Outdoor & Garden',
        idpath: [10100245],
        name: 'Outdoor & Garden',
        disabled: false,
        id: 10100245,
        leaf: false,
      },
      {
        path: ['Household Supplies'],
        spell: 'Household Supplies',
        idpath: [10100539],
        name: 'Household Supplies',
        disabled: false,
        id: 10100539,
        leaf: false,
      },
      {
        path: ['Large Appliances'],
        spell: 'Large Appliances',
        idpath: [10100871],
        name: 'Large Appliances',
        disabled: false,
        id: 10100871,
        leaf: false,
      },
      {
        path: ['Health'],
        spell: 'Health',
        idpath: [10100869],
        name: 'Health',
        disabled: false,
        id: 10100869,
        leaf: false,
      },
      {
        path: ["Men's Shoes and Clothing"],
        spell: "Men's Shoes and Clothing",
        idpath: [10100758],
        name: "Men's Shoes and Clothing",
        disabled: false,
        id: 10100758,
        leaf: false,
      },
      {
        path: ['Digital Goods'],
        spell: 'Digital Goods',
        idpath: [12576],
        name: 'Digital Goods',
        disabled: false,
        id: 12576,
        leaf: false,
      },
      {
        path: ['Toys & Games'],
        spell: 'Toys & Games',
        idpath: [18443],
        name: 'Toys & Games',
        disabled: false,
        id: 18443,
        leaf: false,
      },
      {
        path: ['Mother & Baby'],
        spell: 'Mother & Baby',
        idpath: [18444],
        name: 'Mother & Baby',
        disabled: false,
        id: 18444,
        leaf: false,
      },
      {
        path: ['Bedding & Bath'],
        spell: 'Bedding & Bath',
        idpath: [22389],
        name: 'Bedding & Bath',
        disabled: false,
        id: 22389,
        leaf: false,
      },
      {
        path: ['Furniture & Organization'],
        spell: 'Furniture & Organization',
        idpath: [22390],
        name: 'Furniture & Organization',
        disabled: false,
        id: 22390,
        leaf: false,
      },
      {
        path: ['Tools & Home Improvement'],
        spell: 'Tools & Home Improvement',
        idpath: [22391],
        name: 'Tools & Home Improvement',
        disabled: false,
        id: 22391,
        leaf: false,
      },
      {
        path: ['Laundry & Cleaning Equipment'],
        spell: 'Laundry & Cleaning Equipment',
        idpath: [22392],
        name: 'Laundry & Cleaning Equipment',
        disabled: false,
        id: 22392,
        leaf: false,
      },
    ],
    pageEnd: true,
    totalPage: 0,
  },
  ret: ['SUCCESS::调用成功'],
  v: '1.0',
}

const categoryPath = {
  api: 'mtop.global.merchant.mobile.product.publish.categoryopts',
  data: {
    context: {},
    model: [
      {
        path: ['Kitchen & Dining', 'Cutlery'],
        spell: 'Cutlery',
        idpath: [22394, 10100151],
        name: 'Cutlery',
        disabled: false,
        id: 10100151,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Disposables'],
        spell: 'Disposables',
        idpath: [22394, 10100180],
        name: 'Disposables',
        disabled: false,
        id: 10100180,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Coffee & Tea'],
        spell: 'Coffee & Tea',
        idpath: [22394, 22420],
        name: 'Coffee & Tea',
        disabled: false,
        id: 22420,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Bakeware'],
        spell: 'Bakeware',
        idpath: [22394, 22415],
        name: 'Bakeware',
        disabled: false,
        id: 22415,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Cookware'],
        spell: 'Cookware',
        idpath: [22394, 22416],
        name: 'Cookware',
        disabled: false,
        id: 22416,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Dinnerware'],
        spell: 'Dinnerware',
        idpath: [22394, 22417],
        name: 'Dinnerware',
        disabled: false,
        id: 22417,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Drinkware'],
        spell: 'Drinkware',
        idpath: [22394, 22418],
        name: 'Drinkware',
        disabled: false,
        id: 22418,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Serveware'],
        spell: 'Serveware',
        idpath: [22394, 22419],
        name: 'Serveware',
        disabled: false,
        id: 22419,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Kitchen Utensils'],
        spell: 'Kitchen Utensils',
        idpath: [22394, 22421],
        name: 'Kitchen Utensils',
        disabled: false,
        id: 22421,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Kitchen & Table Linen'],
        spell: 'Kitchen & Table Linen',
        idpath: [22394, 22422],
        name: 'Kitchen & Table Linen',
        disabled: false,
        id: 22422,
        leaf: false,
      },
      {
        path: ['Kitchen & Dining', 'Kitchen Storage & Accessories'],
        spell: 'Kitchen Storage & Accessories',
        idpath: [22394, 22423],
        name: 'Kitchen Storage & Accessories',
        disabled: false,
        id: 22423,
        leaf: false,
      },
    ],
    pageEnd: true,
    totalPage: 0,
  },
  ret: ['SUCCESS::调用成功'],
  v: '1.0',
}
