const notifCategory = {
  api: 'mtop.lazada.notification.category.unreadmsgcount',
  data: {
    data: [
      {
        categoryCode: 'important_msg',
        categoryId: 7001,
        diaplayName: 'Important',
        displayName: 'Important',
        lastMsg: '',
        number: 0,
        seq: 2147483647,
        subCategoryMsgCount: [
          {
            categoryId: 10003,
            displayName: 'Store',
            lastMsg: '',
            seq: 0,
            subCategoryCode: '',
            subCategoryIds: '1000305,1000306',
          },
          {
            categoryId: 10005,
            displayName: 'Programs',
            lastMsg: '',
            seq: 0,
            subCategoryCode: '',
            subCategoryIds: '1000501,1000502',
          },
        ],
      },
      {
        categoryCode: 'order_notice',
        categoryId: 10001,
        categoryKey: 'iopnotify.notification.category.order',
        diaplayName: 'Order',
        displayName: 'Order',
        lastMsg: '',
        number: 1,
        seq: 6,
        subCategoryMsgCount: [
          {
            categoryId: 10001,
            displayName: 'Exchange Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Exchange_Order',
            subCategoryId: 1000105,
            subCategoryKey: 'iopnotify.notification.scenerio.exchange_order',
          },
          {
            categoryId: 10001,
            displayName: 'Cancelled Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'order_cancel',
            subCategoryId: 1000102,
            subCategoryKey: 'iopnotify.notification.scenerio.cancelled_order',
          },
          {
            categoryId: 10001,
            displayName: 'New Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'order_new',
            subCategoryId: 1000101,
            subCategoryKey: 'iopnotify.notification.scenerio.new_order',
          },
          {
            categoryId: 10001,
            displayName: 'Return Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'order_return',
            subCategoryId: 1000103,
            subCategoryKey: 'iopnotify.notification.scenerio.return_order',
          },
          {
            categoryId: 10001,
            displayName: 'Shipped Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'order_ship',
            subCategoryId: 1000104,
            subCategoryKey: 'iopnotify.notification.scenerio.shipped_order',
          },
        ],
      },
      {
        categoryCode: 'Logistics',
        categoryId: 10007,
        categoryKey: 'iopnotify.notification.category.logistics',
        diaplayName: 'Logistics',
        displayName: 'Logistics',
        lastMsg: '',
        number: 0,
        seq: 5,
        subCategoryMsgCount: [
          {
            categoryId: 10007,
            displayName: 'Logistics',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Logistics',
            subCategoryId: 1000701,
            subCategoryKey: 'iopnotify.notification.scenerio.logistics',
          },
        ],
      },
      {
        categoryCode: 'Store',
        categoryId: 10003,
        categoryKey: 'iopnotify.notification.category.store',
        diaplayName: 'Store',
        displayName: 'Store',
        lastMsg: '',
        number: 0,
        seq: 4,
        subCategoryMsgCount: [
          {
            categoryId: 10003,
            displayName: 'Account Manager',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Account_Manager',
            subCategoryId: 1000305,
            subCategoryKey: 'iopnotify.notification.scenerio.account_manager',
          },
          {
            categoryId: 10003,
            displayName: 'Finance',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Finance',
            subCategoryId: 1000302,
            subCategoryKey: 'iopnotify.notification.scenerio.finance',
          },
          {
            categoryId: 10003,
            displayName: 'New Seller Guide',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'New_Seller_Guide',
            subCategoryId: 1000304,
            subCategoryKey: 'iopnotify.notification.scenerio.new_seller_guide',
          },
          {
            categoryId: 10003,
            displayName: 'Policy Violations',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Policy_Violations',
            subCategoryId: 1000306,
            subCategoryKey: 'iopnotify.notification.scenerio.policy_violations',
          },
          {
            categoryId: 10003,
            displayName: 'Product',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Product',
            subCategoryId: 1000301,
            subCategoryKey: 'iopnotify.notification.scenerio.product',
          },
          {
            categoryId: 10003,
            displayName: 'Service Marketplace',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Service_Marketplace',
            subCategoryId: 1000307,
            subCategoryKey:
              'iopnotify.notification.scenerio.service_marketplace',
          },
          {
            categoryId: 10003,
            displayName: 'Store Promotion',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Store_Promotion',
            subCategoryId: 1000303,
            subCategoryKey: 'iopnotify.notification.scenerio.store_promotion',
          },
        ],
      },
      {
        categoryCode: 'Systems',
        categoryId: 10004,
        categoryKey: 'iopnotify.notification.category.system',
        diaplayName: 'Systems',
        displayName: 'Systems',
        lastMsg: '',
        number: 0,
        seq: 3,
        subCategoryMsgCount: [
          {
            categoryId: 10004,
            displayName: 'Policy Updates',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Policy_Updates',
            subCategoryId: 1000402,
            subCategoryKey: 'iopnotify.notification.scenerio.policy_updates',
          },
          {
            categoryId: 10004,
            displayName: 'Survey',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Survey',
            subCategoryId: 1000403,
            subCategoryKey: 'iopnotify.notification.scenerio.survey',
          },
          {
            categoryId: 10004,
            displayName: 'System Updates',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'System_Updates',
            subCategoryId: 1000401,
            subCategoryKey: 'iopnotify.notification.scenerio.system_updates',
          },
        ],
      },
      {
        categoryCode: 'Programs',
        categoryId: 10005,
        categoryKey: 'iopnotify.notification.category.programs',
        diaplayName: 'Programs',
        displayName: 'Programs',
        lastMsg: '',
        number: 0,
        seq: 2,
        subCategoryMsgCount: [
          {
            categoryId: 10005,
            displayName: 'Campaign',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Campaign',
            subCategoryId: 1000501,
            subCategoryKey: 'iopnotify.notification.scenerio.campaign',
          },
          {
            categoryId: 10005,
            displayName: 'LazLive',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'LazLive',
            subCategoryId: 324161,
            subCategoryKey: 'medKey_58275316548068124',
          },
          {
            categoryId: 10005,
            displayName: 'Platform Promotion',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Platform_Promotion',
            subCategoryId: 1000502,
            subCategoryKey:
              'iopnotify.notification.scenerio.platform_promotion',
          },
          {
            categoryId: 10005,
            displayName: 'LazCoins',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Programs_LazCoins',
            subCategoryId: 1000505,
            subCategoryKey: 'iopnotify.notification.scenerio.lazcoins',
          },
          {
            categoryId: 10005,
            displayName: 'Seller Programs',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Seller_Programs',
            subCategoryId: 1000504,
            subCategoryKey: 'iopnotify.notification.scenerio.seller_programs',
          },
          {
            categoryId: 10005,
            displayName: 'Sponsored Solution',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Sponsored_Solution',
            subCategoryId: 1000503,
            subCategoryKey:
              'iopnotify.notification.scenerio.sponsored_solution',
          },
        ],
      },
      {
        categoryCode: 'Learn_And_Grow',
        categoryId: 10006,
        categoryKey: 'iopnotify.notification.category.learn_and_grow',
        diaplayName: 'Learn & Grow',
        displayName: 'Learn & Grow',
        lastMsg: '',
        number: 0,
        seq: 1,
        subCategoryMsgCount: [
          {
            categoryId: 10006,
            displayName: 'Business Advisor',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Business_Advisor',
            subCategoryId: 1000603,
            subCategoryKey: 'iopnotify.notification.scenerio.business_advisor',
          },
          {
            categoryId: 10006,
            displayName: 'Incubation',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Incubation',
            subCategoryId: 1000601,
            subCategoryKey: 'iopnotify.notification.scenerio.incubation',
          },
          {
            categoryId: 10006,
            displayName: 'Lazada University',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Lazada_University',
            subCategoryId: 1000602,
            subCategoryKey: 'iopnotify.notification.scenerio.lazada_university',
          },
          {
            categoryId: 10006,
            displayName: 'Seller Community',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Seller_Community',
            subCategoryId: 499085,
            subCategoryKey: 'medKey_52191270702464378',
          },
        ],
      },
      {
        categoryCode: 'customer_care',
        categoryId: 10008,
        categoryKey: 'iopnotify.notification.category.customer_care',
        diaplayName: 'Customer Care',
        displayName: 'Customer Care',
        lastMsg: '',
        number: 0,
        seq: -1,
        subCategoryMsgCount: [
          {
            categoryId: 10008,
            displayName: 'Case Update',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Case_Update',
            subCategoryId: 787909,
            subCategoryKey: 'medKey_3421524782193146',
          },
          {
            categoryId: 10008,
            displayName: 'General Notification',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'General_Notification',
            subCategoryId: 90828,
            subCategoryKey: 'medKey_43942143322032706',
          },
          {
            categoryId: 10008,
            displayName: 'Information Alert',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Information_Alert',
            subCategoryId: 797180,
            subCategoryKey: 'medKey_5121861358252742',
          },
        ],
      },
    ],
  },
  ret: ['SUCCESS::调用成功'],
  v: '1.0',
}
const notifItem = {
  api: 'mtop.lazada.notification.getmsglistbycategory',
  data: {
    data: {
      dataSource: [
        {
          bizData: {
            extraData:
              '{"subOrderIcon":"https://ph-live.slatic.net/p/42fe2a2648f4e3ca07d8cb76ab5452b8.png","pc_jump_link":"https://sellercenter-staging.lazada.com.ph/apps/order/list?oldVersion=1&spm=a1zawj.17752401.navi_left_sidebar.droot_normal_ordersreviews_ordersnewui.4e5c4edfD4fO0d&status=toRespond?tradeOrderId=850685829608976","sellerId":"500379936040","notifyType":"newNotify","businessTenant":"MARKETPLACE","templateStyleId":"2001","subOrderTitle":"Red Wine XT100","buyerUserId":"500035608976","order_id":"850685829608976","seller_app_jump_link":"lazadaseller://com.sc.lazada/order/v3/detail?orderid=850685829608976"}',
            url: 'lazadaseller://com.sc.lazada/order/v3/detail?orderid=850685829608976',
          },
          categoryId: 10001,
          detail:
            '<div><div style="margin-top: 50px;"><a href="https://sellercenter-staging.lazada.com.ph/apps/order/list?oldVersion=1&spm=a1zawj.17752401.navi_left_sidebar.droot_normal_ordersreviews_ordersnewui.4e5c4edfD4fO0d&status=toRespond?tradeOrderId=850685829608976" target="_blank">See more Detail</a></div></div>',
          fkTemplateId: 3918,
          gmtCreate: 1718358291000,
          id: '398758716127329266',
          message: {
            appLink:
              'lazadaseller://com.sc.lazada/order/v3/detail?orderid=850685829608976',
            categoryCode: 'order_notice',
            categoryId: 10001,
            categoryName: 'Order',
            description: 'Order Number:850685829608976',
            displayName: 'Cancelled Order',
            imageUrl:
              'https://ph-live.slatic.net/p/42fe2a2648f4e3ca07d8cb76ab5452b8.png',
            mark: true,
            notifyType: 'newNotify',
            picture:
              'https://ph-live.slatic.net/p/42fe2a2648f4e3ca07d8cb76ab5452b8.png',
            subCategoryCode: '1000102',
            subCategoryId: 1000102,
            subCategoryName: 'Cancelled Order',
            title: 'Order has been successfully cancelled - test',
            webLink:
              'https://sellercenter-staging.lazada.com.ph/apps/order/list?oldVersion=1&spm=a1zawj.17752401.navi_left_sidebar.droot_normal_ordersreviews_ordersnewui.4e5c4edfD4fO0d&status=toRespond?tradeOrderId=850685829608976',
          },
          requirementId: 577,
          time: '0 minutes ago',
        },
        {
          bizData: {
            extraData:
              '{"orderNumber":"850685829608976","orderurl":"https://sellercenter.lazada.com.ph/apps/order/detail?tradeOrderId=850685829608976","notifyType":"newNotify","apppicture":"https://ph-live.slatic.net/p/42fe2a2648f4e3ca07d8cb76ab5452b8.png","businessTenant":"MARKETPLACE","templateStyleId":"2001","apporderurl":"lazadaseller://com.sc.lazada/order/detail?orderId=850685829608976"}',
            url: 'lazadaseller://com.sc.lazada/order/detail?orderId=850685829608976',
          },
          categoryId: 10001,
          detail:
            '<div><div style="margin-top: 50px;"><a href="https://sellercenter.lazada.com.ph/apps/order/detail?tradeOrderId=850685829608976" target="_blank">See more Detail</a></div></div>',
          fkTemplateId: 3363,
          gmtCreate: 1718358291000,
          id: '398758678575782412',
          message: {
            appLink:
              'lazadaseller://com.sc.lazada/order/detail?orderId=850685829608976',
            categoryCode: 'order_notice',
            categoryId: 10001,
            categoryName: 'Order',
            description: 'Order Number: 850685829608976',
            displayName: 'Cancelled Order',
            mark: true,
            notifyType: 'newNotify',
            subCategoryCode: '1000102',
            subCategoryId: 1000102,
            subCategoryName: 'Cancelled Order',
            title: 'Order has been cancelled',
            webLink:
              'https://sellercenter.lazada.com.ph/apps/order/detail?tradeOrderId=850685829608976',
          },
          requirementId: 622,
          time: '0 minutes ago',
        },
        {
          bizData: {
            extraData:
              '{"orderNumber":"850685829608976","orderurl":"https://sellercenter.lazada.com.ph/apps/order/detail?tradeOrderId=850685829608976","notifyType":"newNotify","apppicture":"https://ph-live.slatic.net/p/42fe2a2648f4e3ca07d8cb76ab5452b8.png","businessTenant":"MARKETPLACE","templateStyleId":"2001","apporderurl":"lazadaseller://com.sc.lazada/order/detail?orderId=850685829608976"}',
            url: 'lazadaseller://com.sc.lazada/order/detail?orderId=850685829608976',
          },
          categoryId: 10001,
          detail:
            '<div><div style="margin-top: 50px;"><a href="https://sellercenter.lazada.com.ph/apps/order/detail?tradeOrderId=850685829608976" target="_blank">See more Detail</a></div></div>',
          fkTemplateId: 3362,
          gmtCreate: 1718093181000,
          id: '114098895524596272',
          message: {
            appLink:
              'lazadaseller://com.sc.lazada/order/detail?orderId=850685829608976',
            categoryCode: 'order_notice',
            categoryId: 10001,
            categoryName: 'Order',
            description: 'Order Number: 850685829608976',
            displayName: 'New Order',
            imageUrl:
              'https://ph-live.slatic.net/p/42fe2a2648f4e3ca07d8cb76ab5452b8.png',
            mark: false,
            notifyType: 'newNotify',
            picture:
              'https://ph-live.slatic.net/p/42fe2a2648f4e3ca07d8cb76ab5452b8.png',
            subCategoryCode: '1000101',
            subCategoryId: 1000101,
            subCategoryName: 'New Order',
            title: "You've got a new order",
            webLink:
              'https://sellercenter.lazada.com.ph/apps/order/detail?tradeOrderId=850685829608976',
          },
          requirementId: 621,
          time: '11/06/2024',
        },
      ],
      pageInfo: { current: 1, pageSize: 10, total: 3 },
    },
  },
  ret: ['SUCCESS::调用成功'],
  v: '1.0',
}

const notifStoreCategory = {
  api: 'mtop.lazada.notification.getmsglistbycategory',
  data: {
    data: {
      dataSource: [
        {
          bizData: {
            extraData:
              '{"en_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","th_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","en_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","th_title":"Avoid store deactivation if you upload your BIR2303 NOW!","id_title":"Avoid store deactivation if you upload your BIR2303 NOW!","cn_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","id_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","notifyType":"oldNotify","id_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","th_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","businessTenant":"MARKETPLACE","en_title":"Avoid store deactivation if you upload your BIR2303 NOW!","cn_title":"Avoid store deactivation if you upload your BIR2303 NOW!","templateStyleId":"2001","vn_title":"Avoid store deactivation if you upload your BIR2303 NOW!","vn_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","cn_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","vn_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","popupContext":"{\\"endTime\\":0,\\"popupBizScene\\":\\"LAZADA_ENGAGEMENT\\",\\"popupContent\\":\\"[{\\\\\\"banner\\\\\\":\\\\\\"\\\\\\",\\\\\\"buttonTxt\\\\\\":\\\\\\"What is this requirement?\\\\\\",\\\\\\"buttonUrl\\\\\\":\\\\\\"https://sellercenter.lazada.com.ph/seller/helpcenter/what-is-the-withholding-tax-235662.html?spm=a2a15.helpcenter-psc-topic.search-box.1.3fb93a0e5SsS85\\\\\\",\\\\\\"contentValue\\\\\\":\\\\\\"<article class=\\\\\\\\\\\\\\"lzd-article\\\\\\\\\\\\\\" style=\\\\\\\\\\\\\\"white-space:break-spaces\\\\\\\\\\\\\\"><p style=\\\\\\\\\\\\\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\\\\\\\\\\\\\"><span></span><img src=\\\\\\\\\\\\\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\\\\\\\\\\\\\" style=\\\\\\\\\\\\\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\\\\\\\\\\\\\"><span></span></p></article>\\\\\\",\\\\\\"description\\\\\\":\\\\\\"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! \\\\\\",\\\\\\"id\\\\\\":\\\\\\"1\\\\\\",\\\\\\"language\\\\\\":\\\\\\"en\\\\\\",\\\\\\"link\\\\\\":\\\\\\"\\\\\\",\\\\\\"needJumpButton\\\\\\":false,\\\\\\"rightButtonTxt\\\\\\":\\\\\\"Upload your requirements NOW! \\\\\\",\\\\\\"rightButtonUrl\\\\\\":\\\\\\"https://sellercenter.lazada.com.ph/apps/setting/business?spm=a1zawj.26007879.configs.d_business.32f54edf2Wlk67\\\\\\",\\\\\\"title\\\\\\":\\\\\\"Avoid store deactivation if you upload your BIR2303 NOW!\\\\\\"}]\\",\\"popupContentId\\":\\"1000027400000093366\\",\\"popupNumberTotal\\":1,\\"popupTriggerType\\":1,\\"popupTypeEnum\\":\\"IMAGE\\"}"}',
            url: '${appLink}',
          },
          businessId: '1000027400000093366',
          businessPart: '_engagement_notification_type_',
          categoryId: 10003,
          detail:
            '<article class="lzd-article" style="white-space:break-spaces"><p style="line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0"><span></span><img src="https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg" style="width:711px;height:461.8729244323958px;display:inline;vertical-align:middle"><span></span></p></article>',
          fkTemplateId: 684,
          gmtCreate: 1719287149000,
          id: '1396112516162010500',
          message: {
            categoryCode: 'Store',
            categoryId: 10003,
            categoryName: 'Store',
            description:
              'All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ',
            displayName: 'Finance',
            mark: true,
            notifyType: 'oldNotify',
            subCategoryCode: '1000302',
            subCategoryId: 1000302,
            subCategoryName: 'Finance',
            title: 'Avoid store deactivation if you upload your BIR2303 NOW!',
          },

          requirementId: 220,
          time: '11:45 AM',
        },
        {
          bizData: {
            extraData:
              '{"en_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","th_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","en_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","th_title":"Avoid store deactivation if you upload your BIR2303 NOW!","id_title":"Avoid store deactivation if you upload your BIR2303 NOW!","cn_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","id_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","notifyType":"oldNotify","id_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","th_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","businessTenant":"MARKETPLACE","en_title":"Avoid store deactivation if you upload your BIR2303 NOW!","cn_title":"Avoid store deactivation if you upload your BIR2303 NOW!","templateStyleId":"2001","vn_title":"Avoid store deactivation if you upload your BIR2303 NOW!","vn_content":"<article class=\\"lzd-article\\" style=\\"white-space:break-spaces\\"><p style=\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\"><span></span><img src=\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\" style=\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\"><span></span></p></article>","cn_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","vn_description":"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ","popupContext":"{\\"endTime\\":0,\\"popupBizScene\\":\\"LAZADA_ENGAGEMENT\\",\\"popupContent\\":\\"[{\\\\\\"banner\\\\\\":\\\\\\"\\\\\\",\\\\\\"buttonTxt\\\\\\":\\\\\\"What is this requirement?\\\\\\",\\\\\\"buttonUrl\\\\\\":\\\\\\"https://sellercenter.lazada.com.ph/seller/helpcenter/what-is-the-withholding-tax-235662.html?spm=a2a15.helpcenter-psc-topic.search-box.1.3fb93a0e5SsS85\\\\\\",\\\\\\"contentValue\\\\\\":\\\\\\"<article class=\\\\\\\\\\\\\\"lzd-article\\\\\\\\\\\\\\" style=\\\\\\\\\\\\\\"white-space:break-spaces\\\\\\\\\\\\\\"><p style=\\\\\\\\\\\\\\"line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0\\\\\\\\\\\\\\"><span></span><img src=\\\\\\\\\\\\\\"https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg\\\\\\\\\\\\\\" style=\\\\\\\\\\\\\\"width:711px;height:461.8729244323958px;display:inline;vertical-align:middle\\\\\\\\\\\\\\"><span></span></p></article>\\\\\\",\\\\\\"description\\\\\\":\\\\\\"All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! \\\\\\",\\\\\\"id\\\\\\":\\\\\\"1\\\\\\",\\\\\\"language\\\\\\":\\\\\\"en\\\\\\",\\\\\\"link\\\\\\":\\\\\\"\\\\\\",\\\\\\"needJumpButton\\\\\\":false,\\\\\\"rightButtonTxt\\\\\\":\\\\\\"Upload your requirements NOW! \\\\\\",\\\\\\"rightButtonUrl\\\\\\":\\\\\\"https://sellercenter.lazada.com.ph/apps/setting/business?spm=a1zawj.26007879.configs.d_business.32f54edf2Wlk67\\\\\\",\\\\\\"title\\\\\\":\\\\\\"Avoid store deactivation if you upload your BIR2303 NOW!\\\\\\"}]\\",\\"popupContentId\\":\\"1000027400000093366\\",\\"popupNumberTotal\\":1,\\"popupTriggerType\\":1,\\"popupTypeEnum\\":\\"IMAGE\\"}"}',
            url: '${appLink}',
          },
          businessId: '1000027400000093366',
          businessPart: '_engagement_notification_type_',
          categoryId: 10003,
          detail:
            '<article class="lzd-article" style="white-space:break-spaces"><p style="line-height:1.7;text-align:left;text-indent:0;margin-left:0;margin-top:0;margin-bottom:0"><span></span><img src="https://img.lazcdn.com/us/sem_seller_engagement_push/71a65423578c3708f66e1ff81488b962.png_2200x2200q80.jpg" style="width:711px;height:461.8729244323958px;display:inline;vertical-align:middle"><span></span></p></article>',
          fkTemplateId: 684,
          gmtCreate: 1719200583000,
          id: '1303162658230063222',
          message: {
            categoryCode: 'Store',
            categoryId: 10003,
            categoryName: 'Store',
            description:
              'All local online sellers are required to upload their BIR2303 and input their TIN in Seller Center NOW! ',
            displayName: 'Finance',
            mark: false,
            notifyType: 'oldNotify',
            subCategoryCode: '1000302',
            subCategoryId: 1000302,
            subCategoryName: 'Finance',
            title: 'Avoid store deactivation if you upload your BIR2303 NOW!',
          },
          requirementId: 220,
          time: 'yesterday',
        },
      ],
      pageInfo: { current: 1, pageSize: 10, total: 2 },
    },
  },
  ret: ['SUCCESS::调用成功'],
  v: '1.0',
}

const unreadMessage = {
  api: 'mtop.lazada.notification.category.unreadmsgcount',
  data: {
    data: [
      {
        categoryCode: 'important_msg',
        categoryId: 7001,
        diaplayName: 'Important',
        displayName: 'Important',
        lastMsg: '',
        number: 0,
        seq: 2147483647,
        subCategoryMsgCount: [
          {
            categoryId: 10003,
            displayName: 'Store',
            lastMsg: '',
            seq: 0,
            subCategoryCode: '',
            subCategoryIds: '1000305,1000306',
          },
          {
            categoryId: 10005,
            displayName: 'Programs',
            lastMsg: '',
            seq: 0,
            subCategoryCode: '',
            subCategoryIds: '1000501,1000502',
          },
        ],
      },
      {
        categoryCode: 'order_notice',
        categoryId: 10001,
        categoryKey: 'iopnotify.notification.category.order',
        diaplayName: 'Order',
        displayName: 'Order',
        lastMsg: '',
        number: 2,
        seq: 6,
        subCategoryMsgCount: [
          {
            categoryId: 10001,
            displayName: 'Exchange Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Exchange_Order',
            subCategoryId: 1000105,
            subCategoryKey: 'iopnotify.notification.scenerio.exchange_order',
          },
          {
            categoryId: 10001,
            displayName: 'Cancelled Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'order_cancel',
            subCategoryId: 1000102,
            subCategoryKey: 'iopnotify.notification.scenerio.cancelled_order',
          },
          {
            categoryId: 10001,
            displayName: 'New Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'order_new',
            subCategoryId: 1000101,
            subCategoryKey: 'iopnotify.notification.scenerio.new_order',
          },
          {
            categoryId: 10001,
            displayName: 'Return Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'order_return',
            subCategoryId: 1000103,
            subCategoryKey: 'iopnotify.notification.scenerio.return_order',
          },
          {
            categoryId: 10001,
            displayName: 'Shipped Order',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'order_ship',
            subCategoryId: 1000104,
            subCategoryKey: 'iopnotify.notification.scenerio.shipped_order',
          },
        ],
      },
      {
        categoryCode: 'Logistics',
        categoryId: 10007,
        categoryKey: 'iopnotify.notification.category.logistics',
        diaplayName: 'Logistics',
        displayName: 'Logistics',
        lastMsg: '',
        number: 0,
        seq: 5,
        subCategoryMsgCount: [
          {
            categoryId: 10007,
            displayName: 'Logistics',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Logistics',
            subCategoryId: 1000701,
            subCategoryKey: 'iopnotify.notification.scenerio.logistics',
          },
        ],
      },
      {
        categoryCode: 'Store',
        categoryId: 10003,
        categoryKey: 'iopnotify.notification.category.store',
        diaplayName: 'Store',
        displayName: 'Store',
        lastMsg: '',
        number: 0,
        seq: 4,
        subCategoryMsgCount: [
          {
            categoryId: 10003,
            displayName: 'Account Manager',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Account_Manager',
            subCategoryId: 1000305,
            subCategoryKey: 'iopnotify.notification.scenerio.account_manager',
          },
          {
            categoryId: 10003,
            displayName: 'Finance',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Finance',
            subCategoryId: 1000302,
            subCategoryKey: 'iopnotify.notification.scenerio.finance',
          },
          {
            categoryId: 10003,
            displayName: 'New Seller Guide',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'New_Seller_Guide',
            subCategoryId: 1000304,
            subCategoryKey: 'iopnotify.notification.scenerio.new_seller_guide',
          },
          {
            categoryId: 10003,
            displayName: 'Policy Violations',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Policy_Violations',
            subCategoryId: 1000306,
            subCategoryKey: 'iopnotify.notification.scenerio.policy_violations',
          },
          {
            categoryId: 10003,
            displayName: 'Product',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Product',
            subCategoryId: 1000301,
            subCategoryKey: 'iopnotify.notification.scenerio.product',
          },
          {
            categoryId: 10003,
            displayName: 'Service Marketplace',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Service_Marketplace',
            subCategoryId: 1000307,
            subCategoryKey:
              'iopnotify.notification.scenerio.service_marketplace',
          },
          {
            categoryId: 10003,
            displayName: 'Store Promotion',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Store_Promotion',
            subCategoryId: 1000303,
            subCategoryKey: 'iopnotify.notification.scenerio.store_promotion',
          },
        ],
      },
      {
        categoryCode: 'Systems',
        categoryId: 10004,
        categoryKey: 'iopnotify.notification.category.system',
        diaplayName: 'Systems',
        displayName: 'Systems',
        lastMsg: '',
        number: 0,
        seq: 3,
        subCategoryMsgCount: [
          {
            categoryId: 10004,
            displayName: 'Policy Updates',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Policy_Updates',
            subCategoryId: 1000402,
            subCategoryKey: 'iopnotify.notification.scenerio.policy_updates',
          },
          {
            categoryId: 10004,
            displayName: 'Survey',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Survey',
            subCategoryId: 1000403,
            subCategoryKey: 'iopnotify.notification.scenerio.survey',
          },
          {
            categoryId: 10004,
            displayName: 'System Updates',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'System_Updates',
            subCategoryId: 1000401,
            subCategoryKey: 'iopnotify.notification.scenerio.system_updates',
          },
        ],
      },
      {
        categoryCode: 'Programs',
        categoryId: 10005,
        categoryKey: 'iopnotify.notification.category.programs',
        diaplayName: 'Programs',
        displayName: 'Programs',
        lastMsg: '',
        number: 0,
        seq: 2,
        subCategoryMsgCount: [
          {
            categoryId: 10005,
            displayName: 'Campaign',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Campaign',
            subCategoryId: 1000501,
            subCategoryKey: 'iopnotify.notification.scenerio.campaign',
          },
          {
            categoryId: 10005,
            displayName: 'LazLive',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'LazLive',
            subCategoryId: 324161,
            subCategoryKey: 'medKey_58275316548068124',
          },
          {
            categoryId: 10005,
            displayName: 'Platform Promotion',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Platform_Promotion',
            subCategoryId: 1000502,
            subCategoryKey:
              'iopnotify.notification.scenerio.platform_promotion',
          },
          {
            categoryId: 10005,
            displayName: 'LazCoins',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Programs_LazCoins',
            subCategoryId: 1000505,
            subCategoryKey: 'iopnotify.notification.scenerio.lazcoins',
          },
          {
            categoryId: 10005,
            displayName: 'Seller Programs',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Seller_Programs',
            subCategoryId: 1000504,
            subCategoryKey: 'iopnotify.notification.scenerio.seller_programs',
          },
          {
            categoryId: 10005,
            displayName: 'Sponsored Solution',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Sponsored_Solution',
            subCategoryId: 1000503,
            subCategoryKey:
              'iopnotify.notification.scenerio.sponsored_solution',
          },
        ],
      },
      {
        categoryCode: 'Learn_And_Grow',
        categoryId: 10006,
        categoryKey: 'iopnotify.notification.category.learn_and_grow',
        diaplayName: 'Learn & Grow',
        displayName: 'Learn & Grow',
        lastMsg: '',
        number: 0,
        seq: 1,
        subCategoryMsgCount: [
          {
            categoryId: 10006,
            displayName: 'Business Advisor',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Business_Advisor',
            subCategoryId: 1000603,
            subCategoryKey: 'iopnotify.notification.scenerio.business_advisor',
          },
          {
            categoryId: 10006,
            displayName: 'Incubation',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Incubation',
            subCategoryId: 1000601,
            subCategoryKey: 'iopnotify.notification.scenerio.incubation',
          },
          {
            categoryId: 10006,
            displayName: 'Lazada University',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Lazada_University',
            subCategoryId: 1000602,
            subCategoryKey: 'iopnotify.notification.scenerio.lazada_university',
          },
          {
            categoryId: 10006,
            displayName: 'Seller Community',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Seller_Community',
            subCategoryId: 499085,
            subCategoryKey: 'medKey_52191270702464378',
          },
        ],
      },
      {
        categoryCode: 'customer_care',
        categoryId: 10008,
        categoryKey: 'iopnotify.notification.category.customer_care',
        diaplayName: 'Customer Care',
        displayName: 'Customer Care',
        lastMsg: '',
        number: 0,
        seq: -1,
        subCategoryMsgCount: [
          {
            categoryId: 10008,
            displayName: 'Case Update',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Case_Update',
            subCategoryId: 787909,
            subCategoryKey: 'medKey_3421524782193146',
          },
          {
            categoryId: 10008,
            displayName: 'General Notification',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'General_Notification',
            subCategoryId: 90828,
            subCategoryKey: 'medKey_43942143322032706',
          },
          {
            categoryId: 10008,
            displayName: 'Information Alert',
            lastMsg: '',
            seq: 0,
            subCategoryCode: 'Information_Alert',
            subCategoryId: 797180,
            subCategoryKey: 'medKey_5121861358252742',
          },
        ],
      },
    ],
  },
  ret: ['SUCCESS::调用成功'],
  v: '1.0',
}

/*  
  - Every change of category will fire unreadMessageCount.
  - And get the notification feed.
*/
